name: DeepArk
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cffi=1.12.3
  - click=7.0
  - cudatoolkit=10.0.130
  - cython=0.29.13
  - freetype=2.9.1
  - intel-openmp=2019.4
  - jpeg=9b
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.16.5
  - numpy-base=1.16.5
  - olefile=0.46
  - openssl=1.0.2t
  - pillow=6.1.0
  - pip=19.2.2
  - pycparser=2.19
  - python=3.6.5
  - pytorch=1.2.0
  - readline=7.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - torchvision=0.4.0
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - cycler==0.10.0
    - h5py==2.10.0
    - joblib==0.13.2
    - kiwisolver==1.1.0
    - matplotlib==3.1.1
    - pandas==0.25.1
    - patsy==0.5.1
    - plotly==4.1.1
    - pyfaidx==0.5.5.2
    - pyparsing==2.4.2
    - pytabix==0.1
    - python-dateutil==2.8.0
    - pytz==2019.2
    - pyyaml==5.1.2
    - retrying==1.3.3
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - seaborn==0.9.0
    - selene-sdk==0.4.8
    - statsmodels==0.10.1

